export const questionsByModule = {
    module1: {
      level1: [
        {
          question: "What is the primary purpose of blockchain technology?",
          options: [
            "To create digital currencies",
            "To provide a decentralized ledger for transactions",
            "To improve internet speed",
            "To facilitate online gaming",
          ],
          type: "multiple",
          correctOptionIndex: 1,
        },
        {
          question: "Aptos is built to enhance scalability and security while maintaining decentralization.",
          description: "Aptos utilizes a unique architecture that separates transaction execution from data storage. This means it can handle more transactions simultaneously, making it faster and more efficient. For example, while one part of the system processes transactions, another can store them securely, ensuring that both processes don’t slow each other down.",
          type: "text",
          correctOptionIndex: 0,
        },
        {
          question: "Which of the following features does Aptos provide?",
          options: [
            "High transaction throughput",
            "Zero transaction fees",
            "Support for multiple programming languages",
            "Inherent centralization",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "What consensus mechanism does Aptos utilize?",
          options: [
            "Proof of Work",
            "Proof of Stake",
            "AptosBFT (Byzantine Fault Tolerance)",
            "Delegated Proof of Stake",
          ],
          type: "multiple",
          correctOptionIndex: 2,
        },
        {
          question: "What programming language is primarily used for developing smart contracts on Aptos?",
          options: ["Solidity", "Move", "Rust", "JavaScript"],
          type: "multiple",
          correctOptionIndex: 1,
        },
        {
          question: "Aptos allows developers to create which types of applications?",
          options: [
            "Decentralized applications (dApps)",
            "Traditional web applications",
            "Mobile applications without blockchain",
            "Games only",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "What does the Aptos architecture look like?",
          description: "This image shows the key components and flow of the Aptos architecture. The modular design allows for independent upgrades, meaning developers can improve one part of the system without disrupting others. For example, if a new security feature is developed, it can be added without halting transactions.",
          type: "image",
          correctOptionIndex: 0,
          imageUrl: "/icons/aptos-architecture-level1.png",
        },
      ],
      level2: [
        {
          question: "What is a smart contract?",
          options: [
            "A digital agreement between parties",
            "A self-executing contract with terms written in code",
            "A traditional legal document",
            "An informal agreement",
          ],
          type: "multiple",
          correctOptionIndex: 1,
        },
        {
          question: "Smart contracts on Aptos can automate transactions and enforce terms without intermediaries.",
          description: "Once deployed, a smart contract operates on its own, executing the rules coded within it. For instance, a smart contract for a loan can automatically transfer funds when certain conditions are met, like the borrower providing collateral, eliminating the need for banks or other institutions.",
          type: "text",
          correctOptionIndex: 0,
        },
        {
          question: "Which of the following is a unique feature of the Move language?",
          options: [
            "It is only for Ethereum smart contracts.",
            "It enables resource safety and flexibility.",
            "It requires extensive gas fees.",
            "It can be used for front-end development.",
          ],
          type: "multiple",
          correctOptionIndex: 1,
        },
        {
          question: "What is the role of the Aptos token (APT)?",
          options: ["Governance and transaction fees", "Rewarding miners", "To store data", "None of the above"],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "How do you deploy a smart contract on Aptos?",
          options: [
            "Using a command line interface and Move CLI",
            "Through a mobile app",
            "By writing it in Solidity",
            "Using Ethereum tools",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "How can developers interact with the Aptos blockchain?",
          options: [
            "Using the Aptos SDK",
            "By manually writing bytecode",
            "Only through the Aptos Explorer",
            "Using Python scripts only",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "Here’s a diagram showing the smart contract lifecycle in Aptos:",
          description: "This diagram illustrates the stages a smart contract goes through from creation to execution. It starts with writing the contract in Move, deploying it to the blockchain, and finally executing it based on user interactions or predefined conditions. Understanding this lifecycle helps developers ensure their contracts are correctly designed and tested before deployment.",
          type: "image",
          correctOptionIndex: 0,
          imageUrl: "/icons/smart-contract-lifecycle.png",
        },
      ],
      level3: [
        {
          question: "What are dApps?",
          options: [
            "Decentralized applications that run on a blockchain",
            "Applications that require a server",
            "Only games available on blockchain",
            "Apps that can only be used offline",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "Aptos's architecture is designed for high throughput and low latency, making it suitable for dApps.",
          description: "This means that Aptos can handle many transactions quickly and efficiently. High throughput allows for many users to interact with dApps simultaneously without delays, while low latency ensures that actions, such as payments or interactions, happen almost instantly, creating a smoother user experience.",
          type: "text",
          correctOptionIndex: 0,
        },
        {
          question: "Which programming concepts are essential for working with Move?",
          options: [
            "Basic programming and resource management",
            "Only object-oriented programming",
            "No programming knowledge required",
            "Knowledge of only Python",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "Which of the following is NOT a benefit of using Aptos for dApp development?",
          options: [
            "Fast transaction speeds",
            "Extensive community support",
            "Complexity of programming",
            "Security features",
          ],
          type: "multiple",
          correctOptionIndex: 2,
        },
        {
          question: "How can you test your smart contracts before deploying them?",
          options: [
            "Using a local testnet",
            "Deploying them directly on the mainnet",
            "Not possible to test",
            "Only through third-party services",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "What is the purpose of the Aptos governance model?",
          options: [
            "To decentralize decision-making processes",
            "To centralize control over the network",
            "To monitor user activity",
            "None of the above",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "This diagram illustrates the key components of a dApp architecture:",
          description: "It shows how different components interact to create a decentralized application. For instance, a dApp typically includes a user interface, smart contracts, and a blockchain network. Understanding how these components work together is crucial for building effective dApps.",
          type: "image",
          correctOptionIndex: 0,
          imageUrl: "/icons/dapp-architecture.png",
        },
      ],
      level4: [
        {
          question: "What is the primary benefit of participating in the Aptos community?",
          options: [
            "Networking with other developers",
            "Access to exclusive information",
            "Learning from shared experiences",
            "All of the above",
          ],
          type: "multiple",
          correctOptionIndex: 3,
        },
        {
          question: "Engaging with the Aptos community can lead to collaboration on open-source projects.",
          description: "This collaboration encourages sharing of knowledge and resources, allowing developers to learn from each other and improve their skills. For example, working on shared codebases can introduce new techniques and practices that enhance individual projects.",
          type: "text",
          correctOptionIndex: 0,
        },
        {
          question: "What platforms are used for community discussions in Aptos?",
          options: ["Discord and Telegram", "Facebook and Instagram", "Only GitHub", "Email only"],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "How can you contribute to Aptos’s development?",
          options: [
            "By providing feedback and contributing code",
            "By only using the platform",
            "Not possible to contribute",
            "By observing others",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "What role does open-source play in the Aptos ecosystem?",
          options: [
            "Promotes transparency and collaboration",
            "Limits innovation",
            "Is not relevant to blockchain",
            "Only for academic purposes",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "Which of the following resources is essential for staying updated on Aptos?",
          options: ["Official Aptos documentation and blog", "Only social media", "Personal blogs", "Gaming forums"],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "This infographic shows how the Aptos community functions:",
          description: "It highlights the roles of developers, users, and governance participants. Understanding these roles can help newcomers identify where they can contribute or find support in their own development efforts.",
          type: "image",
          correctOptionIndex: 0,
          imageUrl: "/icons/community-function.png",
        },
        {
          question: "What are the advantages of a decentralized governance model?",
          options: [
            "Diverse perspectives and increased accountability",
            "Centralized decision-making",
            "Limited user participation",
            "Higher costs for governance participation",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
      ],
    },
  
    module2: {
      level1: [
        {
          question: "What are the key components of the Aptos architecture?",
          options: [
            "Modules, Resources, and Transactions",
            "Nodes, Miners, and Validators",
            "Servers, Clients, and Databases",
            "Clients, APIs, and Libraries",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "Aptos utilizes a modular architecture that separates execution from storage. This design enhances scalability and flexibility, enabling the network to efficiently manage increasing transaction volumes and adapt to future requirements. Can you explain how this architecture benefits developers and users?",
          description: "This modular design means that different parts of the system can be upgraded independently. For developers, this allows them to work on new features or fixes without affecting the entire network. For users, it translates to a smoother experience as improvements are rolled out without downtime.",
          type: "text",
          correctOptionIndex: 0,
        },
        {
          question: "What is the primary purpose of Aptos's modular design?",
          options: [
            "To limit scalability",
            "To enhance transaction speed and flexibility",
            "To centralize control",
            "To simplify user experience",
          ],
          type: "multiple",
          correctOptionIndex: 1,
        },
        {
          question: "Which component is responsible for managing state and transactions in Aptos?",
          options: ["Execution layer", "Storage layer", "Network layer", "User interface"],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "How does Aptos ensure high throughput in transactions?",
          options: [
            "By batching transactions",
            "Using Proof of Work",
            "Limiting user access",
            "Deploying multiple blockchains",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "The diagram below illustrates the key components of the Aptos architecture. It highlights how these components interact to deliver a scalable and efficient blockchain solution. What insights can you gain from this architecture regarding its modular design and functionality?",
          description: "The diagram showcases how the execution and storage layers communicate. This separation allows for efficient resource use, meaning that as more users join, the system can scale without performance drops, making it ideal for large applications.",
          type: "image",
          correctOptionIndex: 0,
          imageUrl: "/icons/aptos-architecture-level2.png",
        },
        {
          question: "What advantages does Aptos's architecture provide for developers?",
          options: [
            "Improved security and flexibility",
            "Higher fees for transactions",
            "Limited access to resources",
            "No need for coding knowledge",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
      ],
      level2: [
        {
          question: "What is the syntax of the Move programming language primarily designed for?",
          options: ["Smart contracts", "Game development", "Web development", "Data analysis"],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "Move's resource-oriented programming model is designed to prevent accidental data duplication, which significantly enhances the safety and integrity of smart contracts. How does this model contribute to more secure and efficient programming practices in blockchain development?",
          description: "By treating resources as unique entities, Move ensures that once a resource is used, it cannot be copied unintentionally. This prevents bugs and vulnerabilities that could arise from duplicated resources, which is crucial for financial applications where integrity is paramount.",
          type: "text",
          correctOptionIndex: 0,
        },
        {
          question: "Which of the following features does Move provide?",
          options: [
            "Resource management and access control",
            "Only basic scripting capabilities",
            "No error handling",
            "Limited support for data structures",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "What is the primary data structure in Move?",
          options: ["Vectors", "Resources", "Objects", "Arrays"],
          type: "multiple",
          correctOptionIndex: 1,
        },
        {
          question: "How can you test your Move smart contracts?",
          options: [
            "Using the Move Unit Testing framework",
            "Only on the mainnet",
            "By deploying them without tests",
            "Not possible to test",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "The image below showcases the syntax and structure of Move programs. It highlights key elements and conventions used in Move, helping developers understand how to write effective smart contracts. What key takeaways do you see from this illustration that could enhance your understanding of Move programming?",
          description: "This image illustrates the core syntax of Move, emphasizing its resource-oriented design. Observing the structure can help developers recognize patterns and practices that lead to safer contract development, such as proper resource handling and error management.",
          type: "image",
          correctOptionIndex: 0,
          imageUrl: "/icons/move-syntax.png",
        },
        {
          question: "What aspect of Move promotes security in contract development?",
          options: [
            "Static typing and resource safety",
            "Dynamic typing",
            "No need for testing",
            "Simplicity of language",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
      ],
      level3: [
        {
          question: "What is a wallet in the context of blockchain?",
          options: [
            "A software application for managing digital assets",
            "A physical storage device for cryptocurrencies",
            "A service for buying and selling stocks",
            "None of the above",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "Aptos wallets play a crucial role in managing private keys and enabling users to interact securely with the blockchain. They ensure that users can safely store their assets and perform transactions without compromising their security. How do these wallets enhance user experience and trust within the Aptos ecosystem?",
          description: "By securely storing private keys and allowing easy access to funds, wallets make interacting with the blockchain user-friendly. For example, users can perform transactions without worrying about their keys being exposed to hackers, thus building trust in the platform.",
          type: "text",
          correctOptionIndex: 0,
        },
        {
          question: "What is a seed phrase?",
          options: [
            "A backup for wallet recovery",
            "A type of password",
            "A transaction verification method",
            "An encryption key",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "How can users secure their Aptos wallets?",
          options: [
            "By using complex passwords and enabling 2FA",
            "Storing passwords in plain text",
            "Sharing seed phrases publicly",
            "None of the above",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "What does a transaction on Aptos require?",
          options: [
            "A valid signature and sufficient balance",
            "Just an email address",
            "No signature needed",
            "Only the wallet address",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "This diagram illustrates the wallet architecture and transaction flow in Aptos:",
          description: "It shows how transactions move from the user’s wallet to the Aptos blockchain, including the role of private keys in signing transactions. Understanding this flow is critical for users to ensure their transactions are secure and efficient.",
          type: "image",
          correctOptionIndex: 0,
          imageUrl: "/icons/wallet-architecture.png",
        },
        {
          question: "What happens if a user loses their seed phrase?",
          options: [
            "They cannot recover their wallet",
            "They can reset it through email",
            "They can recover it with support",
            "Nothing happens",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
      ],
      level4: [
        {
          question: "What is Aptos governance?",
          options: [
            "The process by which community members influence the development of the platform",
            "Only for the developers",
            "A way to centralize power",
            "A marketing strategy",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "Aptos governance allows token holders to vote on proposals that affect the ecosystem.",
          description: "This system ensures that all stakeholders have a voice in decision-making. For instance, if a new feature is proposed, token holders can vote to approve or reject it, fostering a sense of community ownership and responsibility.",
          type: "text",
          correctOptionIndex: 0,
        },
        {
          question: "What is the role of APT tokens in governance?",
          options: [
            "They grant voting rights on proposals",
            "They have no influence",
            "They are only for trading",
            "They are not necessary for governance",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "How can community members propose changes to the Aptos ecosystem?",
          options: [
            "By submitting proposals to the governance forum",
            "Only by talking in chat rooms",
            "Not allowed to propose",
            "Through social media posts",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "What is the primary benefit of decentralized governance in Aptos?",
          options: [
            "Empowers users and increases transparency",
            "Reduces user participation",
            "Centralizes control over decisions",
            "Limits innovation",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
        {
          question: "The infographic below depicts the Aptos governance process:",
          description: "It outlines the steps from proposal submission to voting outcomes. This visualization can help community members understand how their input can shape the platform’s future and encourages active participation.",
          type: "image",
          correctOptionIndex: 0,
          imageUrl: "/icons/governance-process.png",
        },
        {
          question: "What can community voting impact in the Aptos ecosystem?",
          options: [
            "Feature development and resource allocation",
            "Only user interface changes",
            "No impact at all",
            "Only governance fees",
          ],
          type: "multiple",
          correctOptionIndex: 0,
        },
      ],
    },
  };
  